### ISSUE TITLE
Why isn't this being done over the latest build of Breadwallet?

### ISSUE THREAD

**Issue by losh11** [mperklin/beerwallet#1]
Why use the old version of Doughwallet, instead of the current Breadwallet?

**Comment by mperklin** [comment]
I used doughwallet as my base because dogecoin uses Scrypt, meaning doughwallet was closer to defcoin than breadwallet was. 

I didn't have much time to port it before Defcon and I figured this was the fastest way to get it published in time. 

Are there any specific features missing from beerwallet that are in breadwallet?

Please feel free to fork the current breadwallet and make it work with defcoin.
